######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 8 17:01:22 2010
######################################################################

TEMPLATE     = app
TARGET       = 
DEPENDPATH  += .
INCLUDEPATH += .

# These enables the program to be used with launcher
QMAKE_CXXFLAGS += -fPIC
QMAKE_LFLAGS   += -pie -rdynamic

# Input
SOURCES += test.cpp
