#!/bin/sh

# Use 50 chars long dummy parameter to reserve place for application name and parameters
# so that we get some space to modify them afterwards. If the length of the application 
# name with parameters is longer than space available, only the params that fully
# fit will be shown in the output of top and ps commands. 
/usr/bin/applauncherd.bin "                                                  "

